name: Unit test

on:
  pull_request:

  workflow_dispatch:

jobs:
  lint:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        run: npm install

      - name: Run unit test
        run: CI=true npm test
